version: "3.3"
services:
    postgres:
      image: "postgres:${POSTGRES_VERSION}"
      container_name: "postgres-default"
      ports:
        - "5432:5432"
      volumes:
        - ./postgres/init/createDatabase.sql:/docker-entrypoint-initdb.d/1-db-schema.sql
        - ./postgres/init/createTables.sql:/docker-entrypoint-initdb.d/2-db-tabels.sql
        - "$PWD/${POSTGRES_VOLUME}:/var/lib/postgresql/data"
      environment:
        - POSTGRES_USER=${POSTGRES_USER}
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        - POSTGRES_DB=${POSTGRES_DB}
